version: 1
# disable typing carousel
snapshot:
  percy-css: |
    #ityped {
      display: none;
    }

# only snapshot these selected files
static-snapshots:
  snapshot-files: 'index.html,404.html,posts/index.html,posts/writing-posts/markdown-syntax-guide/index.html'
